// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Feed Feed
//
// swagger:model feed
type Feed struct {

	// the User Id
	ID int64 `json:"id" binding:"required"`

	// the User Name
	Name string `json:"name" binding:"required"`

	// the User Gender
	Gender string `json:"gender" binding:"required"`

	// the User Age
	Age int64 `json:"age" binding:"required"`

	// the User Location
	Location string `json:"location" binding:"required"`
}

// Validate validates this feed
func (m *Feed) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this feed based on context it is used
func (m *Feed) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Feed) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Feed) UnmarshalBinary(b []byte) error {
	var res Feed
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
