// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HTTPValidationErrorDetail http validation error detail
//
// swagger:model httpValidationErrorDetail
type HTTPValidationErrorDetail struct {

	// Error describing field validation failure
	Error string `json:"error,omitempty"`

	// Indicates how the invalid field was provided
	In string `json:"in,omitempty"`

	// Key of field failing validation
	Key string `json:"key,omitempty"`
}

// Validate validates this http validation error detail
func (m *HTTPValidationErrorDetail) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this http validation error detail based on context it is used
func (m *HTTPValidationErrorDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPValidationErrorDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPValidationErrorDetail) UnmarshalBinary(b []byte) error {
	var res HTTPValidationErrorDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
