// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JWT Json Web Token
//
// swagger:model jWT
type JWT struct {

	// the Token
	Token string `json:"token" binding:"required"`
}

// Validate validates this j w t
func (m *JWT) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this j w t based on context it is used
func (m *JWT) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JWT) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JWT) UnmarshalBinary(b []byte) error {
	var res JWT
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
