// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LoginUserRequest Login User Request
//
// swagger:model loginUserRequest
type LoginUserRequest struct {

	// the Email
	Email string `json:"email" binding:"required"`

	// the Password
	Password string `json:"password" binding:"required"`
}

// Validate validates this login user request
func (m *LoginUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this login user request based on context it is used
func (m *LoginUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LoginUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LoginUserRequest) UnmarshalBinary(b []byte) error {
	var res LoginUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
