// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PublicHTTPValidationError public Http validation error
//
// swagger:model publicHttpValidationError
type PublicHTTPValidationError struct {

	// success
	// Example: true
	// Required: true
	Success bool `json:"success"`

	// Short, human-readable description of the error
	// Example: User is lacking permission to access this resource
	Message string `json:"message,omitempty"`

	// data
	Data *PublicHTTPValidationErrorData `json:"data,omitempty"`
}

// Validate validates this public Http validation error
func (m *PublicHTTPValidationError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSuccess(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PublicHTTPValidationError) validateSuccess(formats strfmt.Registry) error {

	if err := validate.Required("success", "body", bool(m.Success)); err != nil {
		return err
	}

	return nil
}

func (m *PublicHTTPValidationError) validateData(formats strfmt.Registry) error {
	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this public Http validation error based on the context it is used
func (m *PublicHTTPValidationError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PublicHTTPValidationError) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if m.Data != nil {

		if swag.IsZero(m.Data) { // not required
			return nil
		}

		if err := m.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PublicHTTPValidationError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublicHTTPValidationError) UnmarshalBinary(b []byte) error {
	var res PublicHTTPValidationError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PublicHTTPValidationErrorData public HTTP validation error data
//
// swagger:model PublicHTTPValidationErrorData
type PublicHTTPValidationErrorData struct {

	// HTTP status code returned for the error
	// Example: 403
	// Maximum: 599
	// Minimum: 100
	Code int64 `json:"status,omitempty"`

	// More detailed, human-readable, optional explanation of the error
	// Example: Forbidden
	Detail string `json:"detail,omitempty"`

	// Type of error returned, should be used for client-side error handling
	// Example: generic
	Type string `json:"type,omitempty"`

	// List of errors received while validating payload against schema
	ValidationErrors []*HTTPValidationErrorDetail `json:"validation_errors"`
}

// Validate validates this public HTTP validation error data
func (m *PublicHTTPValidationErrorData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidationErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PublicHTTPValidationErrorData) validateCode(formats strfmt.Registry) error {
	if swag.IsZero(m.Code) { // not required
		return nil
	}

	if err := validate.MinimumInt("data"+"."+"status", "body", m.Code, 100, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("data"+"."+"status", "body", m.Code, 599, false); err != nil {
		return err
	}

	return nil
}

func (m *PublicHTTPValidationErrorData) validateValidationErrors(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidationErrors) { // not required
		return nil
	}

	for i := 0; i < len(m.ValidationErrors); i++ {
		if swag.IsZero(m.ValidationErrors[i]) { // not required
			continue
		}

		if m.ValidationErrors[i] != nil {
			if err := m.ValidationErrors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("data" + "." + "validation_errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("data" + "." + "validation_errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this public HTTP validation error data based on the context it is used
func (m *PublicHTTPValidationErrorData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateValidationErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PublicHTTPValidationErrorData) contextValidateValidationErrors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ValidationErrors); i++ {

		if m.ValidationErrors[i] != nil {

			if swag.IsZero(m.ValidationErrors[i]) { // not required
				return nil
			}

			if err := m.ValidationErrors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("data" + "." + "validation_errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("data" + "." + "validation_errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PublicHTTPValidationErrorData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublicHTTPValidationErrorData) UnmarshalBinary(b []byte) error {
	var res PublicHTTPValidationErrorData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
