// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Swipe Swipe
//
// swagger:model swipe
type Swipe struct {

	// the Id
	ID int64 `json:"id" binding:"required"`

	// the From User Id
	FromUserID int64 `json:"from_user_id" binding:"required"`

	// the To User Id
	ToUserID int64 `json:"to_user_id" binding:"required"`

	// created at
	// Format: date-time
	CreatedAt CreatedAt `json:"created_at,omitempty"`

	// swipe type
	SwipeType SwipeType `json:"swipe_type,omitempty"`
}

// Validate validates this swipe
func (m *Swipe) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSwipeType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Swipe) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := m.CreatedAt.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("created_at")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("created_at")
		}
		return err
	}

	return nil
}

func (m *Swipe) validateSwipeType(formats strfmt.Registry) error {
	if swag.IsZero(m.SwipeType) { // not required
		return nil
	}

	if err := m.SwipeType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("swipe_type")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("swipe_type")
		}
		return err
	}

	return nil
}

// ContextValidate validate this swipe based on the context it is used
func (m *Swipe) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCreatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSwipeType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Swipe) contextValidateCreatedAt(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := m.CreatedAt.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("created_at")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("created_at")
		}
		return err
	}

	return nil
}

func (m *Swipe) contextValidateSwipeType(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.SwipeType) { // not required
		return nil
	}

	if err := m.SwipeType.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("swipe_type")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("swipe_type")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Swipe) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Swipe) UnmarshalBinary(b []byte) error {
	var res Swipe
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
