swagger: "2.0"
info:
  title: Auth request definitions
  version: 0.0.4
paths: {}
definitions:

  SignupUserRequest:
    title: Signup User Request
    type: object
    properties:
      email:
        description: the Email
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        type: string
      password:
        description: the Password
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        type: string
      name:
        description: the Name
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        type: string
      gender:
        $ref: '../definitions/enum.yaml#/definitions/Gender'
        description: the Gender
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
      birth_date:
        description: the Birth Date
        type: string
        format: string
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
      location:
        $ref: '../definitions/enum.yaml#/definitions/Location'
        description: the Location
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
      profile_picture_url:
        description: the Profile Picture URL
        type: string
        format: uri
        x-omitempty: false
        x-nullable: false

  LoginUserRequest:
    title: Login User Request
    type: object
    properties:
      email:
        description: the Email
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        type: string
      password:
        description: the Password
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        type: string