swagger: "2.0"
info:
  description: Golang Boilerplate Documentation
  title: Golang Boilerplate Service API
  version: 0.0.4
consumes:
  - application/json
produces:
  - application/json
basePath: /v1/api
paths: {}
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: |-
      Access token for application access, **must** include "Bearer " prefix.
      Example: `Bearer b4a94a42-3ea2-4af3-9699-8bcbfee6e6d2`
    x-keyPrefix: "Bearer "
