swagger: "2.0"
info:
  title: Book definitions
  version: 0.0.4
paths: {}
definitions:

  Book:
    title: Book
    type: object
    x-omitempty: false
    x-nullable: true
    properties:
      id:
        description: the Id
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 1
        type: integer
      title:
        description: the Title
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 2
        type: string
      author:
        description: the Author
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 3
        type: string
