swagger: "2.0"
info:
  title: Enum definitions
  version: 0.0.4
paths: {}
definitions:

  Gender:
    title: User Gender
    type: string
    enum:
      - MALE
      - FEMALE
  
  Location:
    title: Location City
    type: string
    enum: 
      - JAKARTA
      - PALEMBANG
      - DENPASAR

  SwipeType:
    title: Swipe Type
    type: string
    enum: 
      - RIGHT
      - LEFT