swagger: "2.0"
info:
  title: Feed definitions
  version: 0.0.4
paths: {}
definitions:

  Preference:
    title: Preference
    type: object
    x-omitempty: false
    x-nullable: true
    properties:
      id:
        description: the Id
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 1
        type: integer
      user_id:
        description: the User Id
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 2
        type: integer
      gender:
        description: the Gender
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 3
        type: string
      min_age:
        description: the Minimum Age
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 4
        type: integer
      max_age:
        description: the Maximum Age
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 5
        type: integer
      location:
        description: the Location
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 6
        type: string
      created_at:
        $ref: './common.yaml#/definitions/CreatedAt'

  Feed:
    title: Feed
    type: object
    x-omitempty: false
    x-nullable: true
    properties:
      id:
        description: the User Id
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 1
        type: integer
      name:
        description: the User Name
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 2
        type: string
      gender:
        description: the User Gender
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 3
        type: string
      age:
        description: the User Age
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 4
        type: integer
      location:
        description: the User Location
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 5
        type: string
      profile_picture_url:
        description: the Profile Picture URL
        type: string
        format: uri
        x-order: 6
        x-omitempty: false
        x-nullable: false

  Swipe:
    title: Swipe
    type: object
    x-omitempty: false
    x-nullable: true
    properties:
      id:
        description: the Id
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 1
        type: integer
      from_user_id:
        description: the From User Id
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 2
        type: integer
      to_user_id:
        description: the To User Id
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 3
        type: integer
      swipe_type:
        description: the Swipe Type
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 4
        $ref: './enum.yaml#/definitions/SwipeType'
      created_at:
        description: the Created At
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 5
        $ref: './common.yaml#/definitions/CreatedAt'