swagger: "2.0"
info:
  title: User definitions
  version: 0.0.4
paths: {}
definitions:

  User:
    title: User
    type: object
    x-omitempty: false
    x-nullable: true
    properties:
      id:
        description: the Id
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 1
        type: integer
      email:
        description: the Email
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 2
        type: string
      password:
        description: the Password
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 3
        type: string
