swagger: "2.0"
info:
  title: User definitions
  version: 0.0.4
paths: {}
definitions:

  User:
    title: User
    type: object
    x-omitempty: false
    x-nullable: true
    properties:
      id:
        description: the Id
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 1
        type: integer
      email:
        description: the Email
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 2
        type: string
      name:
        description: the Name
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 3
        type: string
      gender:
        description: the Gender
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 4
        type: string
      birth_date:
        description: the Birth Date
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 5
        type: string
      location:
        description: the Location
        x-go-custom-tag: 'binding:"required"'
        x-omitempty: false
        x-nullable: false
        x-order: 6
        type: string
      created_at:
        $ref: './common.yaml#/definitions/CreatedAt'