swagger: "2.0"
info:
  title: Feed response definitions
  version: 0.0.4
paths: {}
definitions:

  CreateFeedPreferenceResponse:
    title: Create Feed Preference Response
    type: object
    properties:
      success:
        type: boolean
        example: true
        x-nullable: false
        x-order: 1
      message:
        example: A success message
        type: string
        x-nullable: false
        x-order: 2
      data:
        x-nullable: false
        x-order: 3
        $ref: '../definitions/feed.yaml#/definitions/Preference'
    required:
      - success

  GetFeedResponse:
    title: Get Feed Response
    type: object
    properties:
      success:
        example: true
        type: boolean
        x-nullable: false
        x-order: 1
      message:
        example: A success message
        type: string
        x-order: 2
      data:
        x-order: 3
        type: array
        items:
          $ref: '../definitions/feed.yaml#/definitions/Feed'
      pagination:
        $ref: '../definitions/common.yaml#/definitions/Pagination'
    required:
      - success