swagger: "2.0"
info:
  title: Book paths
  version: 0.0.4
paths:

  /books:
    post:
      description: Create Book
      summary: CreateBook_POST
      operationId: CreateBook
      tags:
        - book
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - $ref: '../definitions/header.yaml#/parameters/XClientId'
        - name: body
          in: body
          required: true
          schema:
            $ref: "../requests/book.yaml#/definitions/CreateBookRequest"
      responses:
        "201":
          description: Create book successfully.
          schema:
            $ref: "../responses/book.yaml#/definitions/CreateBookResponse"
        "400":
          $ref: "../responses/error.yaml#/responses/ValidationErrorResponse"
        "401":
          $ref: "../responses/error.yaml#/responses/AuthUnauthorizedResponse"
        "409":
          $ref: "../responses/error.yaml#/responses/ConflictErrorResponse"
        "500":
          $ref: "../responses/error.yaml#/responses/InternalServerErrorResponse"

    get:
      description: Get Book List
      summary: GetBookList_GET
      operationId: GetBookList
      tags:
        - book
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - $ref: '../definitions/header.yaml#/parameters/XClientId'
        - $ref: '../definitions/header.yaml#/parameters/Authorization'
        - $ref: '../definitions/header.yaml#/parameters/CacheControl'
        - $ref: '../definitions/param.yaml#/parameters/PaginationPage'
        - $ref: '../definitions/param.yaml#/parameters/PaginationSize'
        - $ref: '../definitions/param.yaml#/parameters/PaginationSort'
      responses:
        "200":
          description: Get book list successfully.
          schema:
            $ref: "../responses/book.yaml#/definitions/GetBookListResponse"
        "400":
          $ref: "../responses/error.yaml#/responses/ValidationErrorResponse"
        "401":
          $ref: "../responses/error.yaml#/responses/AuthUnauthorizedResponse"
        "500":
          $ref: "../responses/error.yaml#/responses/InternalServerErrorResponse"
      security:
        - bearerAuth: []